package com.app.main.models;
// Generated Apr 3, 2021, 11:02:42 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AmountTime generated by hbm2java
 */
@Entity
@Table(name = "amount_time", catalog = "data_shop")
public class AmountTime implements java.io.Serializable {

	private Integer id;
	private Integer amountTime;
	private Set<Product> products = new HashSet<Product>(0);

	public AmountTime() {
	}

	public AmountTime(Integer amountTime, Set<Product> products) {
		this.amountTime = amountTime;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "amount_time")
	public Integer getAmountTime() {
		return this.amountTime;
	}

	public void setAmountTime(Integer amountTime) {
		this.amountTime = amountTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "amountTime")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
