package com.app.main.models;
// Generated Apr 3, 2021, 11:02:42 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Auction generated by hbm2java
 */
@Entity
@Table(name = "auction", catalog = "data_shop")
public class Auction implements java.io.Serializable {

	private Integer id;
	private Product product;
	private Users users;
	private Double price;
	private Date time;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Auction() {
	}

	public Auction(Product product, Users users, Double price, Date time, Set<Invoice> invoices) {
		this.product = product;
		this.users = users;
		this.price = price;
		this.time = time;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
//	@JsonFormat(timezone = "GMT+07:00")
//	@DateTimeFormat(pattern = "dd/MM/yyyy HH:ii:ss")
	public Date getTime() {
		return this.time;
	}
//	@JsonFormat(timezone = "GMT+07:00")
	public void setTime(Date time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auction")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
